/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import Modelo.Usuarios;
import Controlador.ControladorAtracciones;
import Controlador.ControladorBookeo;
import Controlador.ControladorSeguimiento;
import Controlador.ControladorUsuarios;
import Modelo.GananciasParque;
import Modelo.ListaAtracciones;
import javax.swing.JOptionPane;
/**
 *
 * @author !Core¡
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal(String nombreUsuario, String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("Menú Principal");
        lblNombreUsuario.setText(nombreUsuario);
        lblTipoUsuario.setText(tipoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdesktopPane = new javax.swing.JDesktopPane();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        jMenuMantenimientos = new javax.swing.JMenu();
        btnAtracciones = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();
        btnBookeo = new javax.swing.JMenuItem();
        btnListado = new javax.swing.JMenuItem();
        btnGanancias = new javax.swing.JMenuItem();
        btnSeguimiento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblTipoUsuario.setText(".");
        jdesktopPane.add(lblTipoUsuario);
        lblTipoUsuario.setBounds(10, 70, 140, 16);

        lblNombreUsuario.setText(".");
        jdesktopPane.add(lblNombreUsuario);
        lblNombreUsuario.setBounds(10, 40, 140, 16);

        jMenuArchivo.setMnemonic('f');
        jMenuArchivo.setText("Archivo");

        btnSalir.setMnemonic('x');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(btnSalir);

        menuBar.add(jMenuArchivo);

        jMenuMantenimientos.setMnemonic('e');
        jMenuMantenimientos.setText("Mantenimientos");

        btnAtracciones.setText("Mantenimiento De Atracciones");
        btnAtracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtraccionesActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnAtracciones);

        btnUsuarios.setText("Mantenimiento De Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnUsuarios);

        btnBookeo.setText("Mantenimiento De Bookeo");
        btnBookeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookeoActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnBookeo);

        btnListado.setText("Mantenimiento De Listado");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnListado);

        btnGanancias.setText("Mantenimiento De Ganancias");
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnGanancias);

        btnSeguimiento.setText("Seguimiento De Atracciones");
        btnSeguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguimientoActionPerformed(evt);
            }
        });
        jMenuMantenimientos.add(btnSeguimiento);

        menuBar.add(jMenuMantenimientos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        frmLogin frmL = new frmLogin();
        frmL.setVisible(true);
        frmL.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        frmRegistroUsuarios frmR = new frmRegistroUsuarios();
        if (lblTipoUsuario.getText().equals("EMPLEADO") || lblTipoUsuario.getText().equals("CLIENTE")) {
            frmR.setVisible(false);
            JOptionPane.showMessageDialog(this, "Solo los Administradores pueden ingresar al registro de usuarios");
        } else if  (lblTipoUsuario.getText().equals("ADMINISTRADOR")){
            jdesktopPane.add(frmR);
            ControladorUsuarios control = new ControladorUsuarios(frmR);
            control.inicio();
            frmR.toFront();
            frmR.setVisible(true);
            frmR.setLocation(jdesktopPane.getWidth() / 2 - frmR.getWidth() / 2, jdesktopPane.getHeight() / 2 - frmR.getHeight() / 2);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAtraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtraccionesActionPerformed
        frmMantenimientoAtracciones frmM = new frmMantenimientoAtracciones();
        if (lblTipoUsuario.getText().equals("EMPLEADO") || lblTipoUsuario.getText().equals("CLIENTE")) {
            frmM.setVisible(false);
            JOptionPane.showMessageDialog(this, "Solo los Administradores pueden ingresar al registro de atracciones");
        } else if (lblTipoUsuario.getText().equals("ADMINISTRADOR")) {
            ControladorAtracciones con = new ControladorAtracciones(frmM);
            con.inicio();
            frmM.toFront();
            frmM.setVisible(true);
            frmM.setLocation(jdesktopPane.getWidth() / 2 - frmM.getWidth() / 2, jdesktopPane.getHeight() / 2 - frmM.getHeight() / 2);
        }
    }//GEN-LAST:event_btnAtraccionesActionPerformed

    private void btnBookeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookeoActionPerformed
        frmBookeo frmb = new frmBookeo();
        if (lblTipoUsuario.getText().equals("EMPLEADO") || lblTipoUsuario.getText().equals("ADMINISTRADOR")) {
            frmb.setVisible(false);
            JOptionPane.showMessageDialog(this, "Solo los clientes pueden ingresar al Bookeo");
        } else if (lblTipoUsuario.getText().equals("CLIENTE")){
            ControladorBookeo con = new ControladorBookeo(frmb);
            con.inicio();
            frmb.toFront();
            frmb.setVisible(true);
            frmb.setLocation(jdesktopPane.getWidth() / 2 - frmb.getWidth() / 2, jdesktopPane.getHeight() / 2 - frmb.getHeight() / 2);
        }
    }//GEN-LAST:event_btnBookeoActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        frmListaAtracciones frmLA = new frmListaAtracciones();
        ListaAtracciones la = new ListaAtracciones(frmLA);
        la.inicio();
        frmLA.toFront();
        frmLA.setVisible(true);
        frmLA.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnSeguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguimientoActionPerformed
        frmSeguimiento frmS = new frmSeguimiento();
        if (lblTipoUsuario.getText().equals("CLIENTE")) {
            frmS.setVisible(false);
            JOptionPane.showMessageDialog(this, "Solo Administradores o Empleados pueden ingresar a esta ventana");
        } else if (lblTipoUsuario.getText().equals("ADMINISTRADOR") || lblTipoUsuario.getText().equals("EMPLEADO")) {
            ControladorSeguimiento con = new ControladorSeguimiento(frmS);
            con.inicio();
            con.inicio2();
            jdesktopPane.add(frmS);
            frmS.toFront();
            frmS.setVisible(true);
            frmS.setLocation(jdesktopPane.getWidth() / 2 - frmS.getWidth() / 2, jdesktopPane.getHeight() / 2 - frmS.getHeight() / 2);
        }
        
    }//GEN-LAST:event_btnSeguimientoActionPerformed

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
        frmGananciasParque frmG = new frmGananciasParque();
        if (lblTipoUsuario.getText().equals("EMPLEADO") || lblTipoUsuario.getText().equals("CLIENTE")) {
            frmG.setVisible(false);
            JOptionPane.showMessageDialog(this, "Solo los Administradores pueden ingresar a esta ventana");
        } else if (lblTipoUsuario.getText().equals("ADMINISTRADOR")) {
            GananciasParque gp = new GananciasParque(frmG);
            gp.inicio();
            gp.inicio2();
            frmG.toFront();
            frmG.setVisible(true);
            frmG.setLocation(jdesktopPane.getWidth() / 2 - frmG.getWidth() / 2, jdesktopPane.getHeight() / 2 - frmG.getHeight() / 2);
        }
    }//GEN-LAST:event_btnGananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal(lblNombreUsuario.getText(), lblTipoUsuario.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAtracciones;
    private javax.swing.JMenuItem btnBookeo;
    private javax.swing.JMenuItem btnGanancias;
    private javax.swing.JMenuItem btnListado;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnSeguimiento;
    public javax.swing.JMenuItem btnUsuarios;
    public javax.swing.JMenu jMenuArchivo;
    public javax.swing.JMenu jMenuMantenimientos;
    private javax.swing.JDesktopPane jdesktopPane;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
